"""empty message

Revision ID: 543ebbb1797f
Revises: 
Create Date: 2022-09-15 15:06:57.207378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '543ebbb1797f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_location_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_base_location', sa.String(length=255), nullable=False),
    sa.Column('comment_base_location', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('comment_base_location'),
    sa.UniqueConstraint('name_base_location')
    )
    op.create_table('base_position_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_base_position', sa.String(length=255), nullable=False),
    sa.Column('comment_base_position', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('comment_base_position'),
    sa.UniqueConstraint('name_base_position')
    )
    op.create_table('carouseles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_carousel', sa.String(length=255), nullable=False),
    sa.Column('dir_carousel', sa.String(length=255), nullable=False),
    sa.Column('number_foto', sa.Integer(), nullable=True),
    sa.Column('date_create', sa.String(length=255), nullable=True),
    sa.Column('dict_all_foto_carousel_name', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('arhive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dir_carousel'),
    sa.UniqueConstraint('name_carousel')
    )
    op.create_table('column_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_element', sa.String(length=255), nullable=False),
    sa.Column('comment_column_element', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('column_element'),
    sa.UniqueConstraint('comment_column_element')
    )
    op.create_table('container_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_container_element', sa.String(length=255), nullable=False),
    sa.Column('comment_container_element', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('comment_container_element'),
    sa.UniqueConstraint('name_container_element')
    )
    op.create_table('height_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height_element', sa.String(length=255), nullable=False),
    sa.Column('comment_height_element', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_height_element'),
    sa.UniqueConstraint('height_element')
    )
    op.create_table('horizontal_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_horizontal_position', sa.String(length=255), nullable=False),
    sa.Column('comment_horizontal_position', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('comment_horizontal_position'),
    sa.UniqueConstraint('name_horizontal_position')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('comments_1', sa.Text(), nullable=True),
    sa.Column('comments_2', sa.Text(), nullable=True),
    sa.Column('comments_3', sa.Text(), nullable=True),
    sa.Column('comments_4', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link'),
    sa.UniqueConstraint('title')
    )
    op.create_table('list_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_model', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_model')
    )
    op.create_table('priority_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('priority_element', sa.Integer(), nullable=True),
    sa.Column('comment_priority_element', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority_element')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('status')
    )
    op.create_table('upload_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu', sa.String(length=255), nullable=False),
    sa.Column('dir_menu', sa.String(length=255), nullable=False),
    sa.Column('dir_usluga', sa.String(length=255), nullable=False),
    sa.Column('origin_name_photo', sa.String(length=255), nullable=False),
    sa.Column('secure_name_photo', sa.String(length=255), nullable=False),
    sa.Column('dir_uploads', sa.String(length=255), nullable=False),
    sa.Column('file_ext', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('usluga', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('user_first_name', sa.String(), nullable=True),
    sa.Column('user_middle_name', sa.String(), nullable=True),
    sa.Column('user_last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vertical_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_vertical_position', sa.String(length=255), nullable=False),
    sa.Column('comment_vertical_position', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('comment_vertical_position'),
    sa.UniqueConstraint('name_vertical_position')
    )
    op.create_table('width_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('width_element', sa.String(length=255), nullable=False),
    sa.Column('comment_width_element', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_width_element'),
    sa.UniqueConstraint('width_element')
    )
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('position_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horizontal_position_id', sa.Integer(), nullable=True),
    sa.Column('vertical_position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horizontal_position_id'], ['horizontal_positions.id'], ),
    sa.ForeignKeyConstraint(['vertical_position_id'], ['vertical_positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('horizontal_position_id', 'vertical_position_id', name='_horizontal_vertical')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('setting_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_export', sa.Boolean(), nullable=True),
    sa.Column('export_max_rows', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['list_models.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'model_id', name='_role_model')
    )
    op.create_table('uslugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('comments_1', sa.Text(), nullable=True),
    sa.Column('comments_2', sa.Text(), nullable=True),
    sa.Column('comments_3', sa.Text(), nullable=True),
    sa.Column('comments_4', sa.Text(), nullable=True),
    sa.Column('punkt_menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['punkt_menu_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link'),
    sa.UniqueConstraint('title')
    )
    op.create_table('cards_uslugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_card_usluga', sa.String(length=255), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('dir_photos', sa.String(length=255), nullable=True),
    sa.Column('usluga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usluga_id'], ['uslugs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dir_photos'),
    sa.UniqueConstraint('name_card_usluga')
    )
    op.create_table('place_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_location_id', sa.Integer(), nullable=False),
    sa.Column('base_position_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('container_element_id', sa.Integer(), nullable=False),
    sa.Column('column_element_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_location_id'], ['base_location_elements.id'], ),
    sa.ForeignKeyConstraint(['base_position_id'], ['base_position_elements.id'], ),
    sa.ForeignKeyConstraint(['column_element_id'], ['column_elements.id'], ),
    sa.ForeignKeyConstraint(['container_element_id'], ['container_elements.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position_elements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_location_id', 'base_position_id', 'position_id', 'container_element_id', 'column_element_id', name='_place_element_relation')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.String(), nullable=False),
    sa.Column('order_create', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_progress', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('order_parameters', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('card_usluga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_usluga_id'], ['cards_uslugs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_usluga_id', sa.Integer(), nullable=True),
    sa.Column('dir_uploads', sa.String(length=255), nullable=False),
    sa.Column('origin_name_photo', sa.String(length=255), nullable=False),
    sa.Column('secure_name_photo', sa.String(length=255), nullable=False),
    sa.Column('file_ext', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['card_usluga_id'], ['cards_uslugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('place_model_elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_model_id', sa.String(), nullable=False),
    sa.Column('place_element_id', sa.Integer(), nullable=False),
    sa.Column('width_element_id', sa.Integer(), nullable=True),
    sa.Column('height_element_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['height_element_id'], ['height_elements.id'], ),
    sa.ForeignKeyConstraint(['name_model_id'], ['list_models.name_model'], ),
    sa.ForeignKeyConstraint(['place_element_id'], ['place_elements.id'], ),
    sa.ForeignKeyConstraint(['width_element_id'], ['width_elements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_element_id', 'name_model_id', 'width_element_id', 'height_element_id', name='_model_place_size')
    )
    op.create_table('price_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_price_table', sa.String(length=255), nullable=False),
    sa.Column('row_table', sa.Integer(), nullable=False),
    sa.Column('col_table', sa.Integer(), nullable=False),
    sa.Column('value_table', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('card_uslugi_id', sa.Integer(), nullable=True),
    sa.Column('card_usluga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_usluga_id'], ['cards_uslugs.id'], ),
    sa.ForeignKeyConstraint(['card_uslugi_id'], ['upload_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_price_table')
    )
    op.create_table('statuses_cards_uslugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('card_usluga_id', sa.Integer(), nullable=False),
    sa.Column('role_responsible_id', sa.Integer(), nullable=True),
    sa.Column('days_norma', sa.Integer(), nullable=True),
    sa.Column('hours_norma', sa.Integer(), nullable=True),
    sa.Column('minutes_norma', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_usluga_id'], ['cards_uslugs.id'], ),
    sa.ForeignKeyConstraint(['role_responsible_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_id', 'card_usluga_id', name='_card_usluga_status')
    )
    op.create_table('place_carousels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carousel_id', sa.Integer(), nullable=False),
    sa.Column('place_model_element_id', sa.Integer(), nullable=False),
    sa.Column('priority_element_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carousel_id'], ['carouseles.id'], ),
    sa.ForeignKeyConstraint(['place_model_element_id'], ['place_model_elements.id'], ),
    sa.ForeignKeyConstraint(['priority_element_id'], ['priority_elements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority_element_id', 'place_model_element_id', 'carousel_id', name='_carousel_place_model_element')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_carousels')
    op.drop_table('statuses_cards_uslugs')
    op.drop_table('price_tables')
    op.drop_table('place_model_elements')
    op.drop_table('photos')
    op.drop_table('orders')
    op.drop_table('place_elements')
    op.drop_table('cards_uslugs')
    op.drop_table('uslugs')
    op.drop_table('setting_admin')
    op.drop_table('roles_users')
    op.drop_table('position_elements')
    op.drop_table('phones')
    op.drop_table('width_elements')
    op.drop_table('vertical_positions')
    op.drop_table('users')
    op.drop_table('upload_files')
    op.drop_table('statuses')
    op.drop_table('roles')
    op.drop_table('priority_elements')
    op.drop_table('list_models')
    op.drop_table('links')
    op.drop_table('horizontal_positions')
    op.drop_table('height_elements')
    op.drop_table('container_elements')
    op.drop_table('column_elements')
    op.drop_table('carouseles')
    op.drop_table('base_position_elements')
    op.drop_table('base_location_elements')
    # ### end Alembic commands ###
